wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710281390.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      4: 3.9.18
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: train_loss
      6:
      - 3
      7:
      - 1
    - 1: train_accuracy
      6:
      - 3
      7:
      - 2
    - 1: train_f1
      6:
      - 3
      7:
      - 2
    - 1: test_loss
      6:
      - 3
      7:
      - 1
    - 1: test_accuracy
      6:
      - 3
      7:
      - 2
    - 1: test_f1
      6:
      - 3
      7:
      - 2
    - 1: validation_loss
      6:
      - 3
      7:
      - 1
    - 1: validation_accuracy
      6:
      - 3
      7:
      - 2
data_path:
  desc: null
  value: cleaneval.csv
dropout:
  desc: null
  value: 0
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.001
model_nr:
  desc: null
  value: 4
num_epochs:
  desc: null
  value: 100
num_layers:
  desc: null
  value: 2
split:
  desc: null
  value: 55-5-676
