wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710277931.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.16.4
      8:
      - 5
      13: darwin-arm64
data_path:
  desc: null
  value: cleaneval.csv
dropout:
  desc: null
  value: 0
hidden_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
model_nr:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 100
num_layers:
  desc: null
  value: 2
split:
  desc: null
  value: 55-5-676
