wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
hidden_size:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 2
dataset:
  desc: null
  value: cleaneval-80-20
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710142725.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 16
      - 23
      4: 3.9.18
      5: 0.16.4
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: loss
      6:
      - 3
      7:
      - 1
    - 1: acc
      6:
      - 3
      7:
      - 2
    - 1: f1
      6:
      - 3
      7:
      - 2
